[tool.poetry]
name = "hojichar"
version = "0.2.0"
description = "Text preprocessing management system."
license = "Apache-2.0"
authors = ["kenta.shinzato <hoppiece@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.23.4"
mmh3 = "^3.0.0"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.lint]
optional = true

[tool.poetry.group.test]
optional = true

[tool.poetry.group.lint.dependencies]
black = "^22.3.0"
flake8 = "^4.0.1"
isort = "^5.10.1"

[tool.poetry.group.test.dependencies]
pytest = "^7.1.2"
mypy = ">=0.982"
pytest-cov = "^4.0.0"

[tool.poetry.group.dev.dependencies]
taskipy = "^1.10.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 99

[tool.isort]
profile = "black"
line_length = 99

[tool.mypy]
ignore_missing_imports = true

[tool.taskipy.tasks]
lint = "flake8 --show-source hojichar/ tests/ && isort --check-only --diff hojichar/ tests/"
format = "black hojichar/ tests/ && isort hojichar/ tests"
test = "pytest . --doctest-modules && mypy ."