name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --with lint,test
      - name: Lint and format check
        run: |
          black --check --diff .
          flake8 --show-source .
          isort --check-only --diff .
        continue-on-error: true
      - name: Test with pytest and doctest
        run: |
          pytest . --doctest-modules
          mypy .
