name: Deploy documents

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  GenenerateDocs:
    name: Deploy documents
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --with doc
      - name: Document generation
        run: |
          pdoc -o docs hojichar

      - name: Check if docs branch exists
        id: check_docs_branch
        run: |
          git remote set-url origin https://github-actions:${{ secrets.GH_ACTIONS_ACCESS_TOKEN }}@github.com/${GITHUB_REPOSITORY}
          git fetch origin
          if ! git show-ref --quiet refs/remotes/origin/docs; then
            echo "::set-output name=branch_exists::false"
          else
            echo "::set-output name=branch_exists::true"
          fi

      - name: Create docs branch if not exists
        if: steps.check_docs_branch.outputs.branch_exists == 'false'
        run: |
          git remote set-url origin https://github-actions:${{ secrets.GH_ACTIONS_ACCESS_TOKEN }}@github.com/${GITHUB_REPOSITORY}
          git checkout -b docs
          git push -u origin docs

      - name: Push new docs
        run: |
          git remote set-url origin https://github-actions:${{ secrets.GH_ACTIONS_ACCESS_TOKEN }}@github.com/${GITHUB_REPOSITORY}
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          if (git diff --shortstat origin/docs | grep '[0-9]'); then \
            git add .; \
            git commit -m "Generating docs via GitHub Actions"; \
            git push origin --force HEAD:docs; \
          fi
