name: Publish PyPI

on:
  release:
    types: [created]

jobs:
  Publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry self add "poetry-dynamic-versioning[plugin]"
      - name: PyPI settings
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
      - name: Build and publish via Poetry
        run: |
          poetry build
          poetry publish
